### ISSUE TITLE
Is there a cli tool equivalent?

### ISSUE THREAD

**Issue by kaelig** [ryanburgess/grunt-sassyclean#3]
I'm not using grunt, so I'd love a cli tool that would tell me which partials are never imported (in a codebase containing 150+ partials).

Do you know of any similar tools that would do that?

**Comment by ryanburgess** [comment]
I could easily convert this to a CLI took if you'd find it useful. I don't use Grunt anymore either and would find it useful as well.

**Comment by ryanburgess** [comment]
Even better I just realized I had created one https://github.com/ryanburgess/sassyclean

**Comment by kaelig** [comment]
Ha! So funny you just remembered it. I'll test it this week, thanks a lot for all the work you've put into it! 

PS: I love the logo

**Comment by ryanburgess** [comment]
You're welcome. Keep me posted on how it goes. There may need to be some features or improvements needed.
